environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CMAKE_GENERATOR: Visual Studio 15 2017
  PLATFORM_TOOLSET: v141_xp
  WEASEL_VERSION: 1.2.3
  WEASEL_BUILD: 4

init:
  - git --version
  - git config --global core.autocrlf true

branches:
  only:
    - master
    - kai_keypad_sooji_tuieng

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

cache:
  - boost.cached -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage_x64 -> appveyor_build_boost.bat

install:
  - .\appveyor.install.bat

build_script:
  # - if "%APPVEYOR_REPO_TAG%" == "false" set WEASEL_BUILD=%APPVEYOR_BUILD_NUMBER%
  - .\build.bat data hant installer
  - ps: $env:BUILD_TIMESTAMP=Get-Date -format yyyyMMddHHmmss
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
  - ps: $BUILD_TIMESTAMP=$env:BUILD_TIMESTAMP
  - ps: $WEASEL_VERSION=$env:WEASEL_VERSION
  - ps: $WEASEL_BUILD=$env:WEASEL_BUILD
  - ps: $GIT_HASH=$env:GIT_HASH
  - ps: echo $WEASEL_VERSION
  - ps: echo $WEASEL_BUILD
  - ps: echo $GIT_HASH
  - ps: echo $BUILD_TIMESTAMP
  - ps: mv output\archives\ThuanTaigi-v$WEASEL_VERSION.$WEASEL_BUILD-installer.exe output\archives\ThuanTaigi-Windows-v$WEASEL_VERSION.$WEASEL_BUILD-$GIT_HASH-$BUILD_TIMESTAMP-installer.exe

artifacts:
  - path: output\archives\ThuanTaigi-Windows-v%WEASEL_VERSION%.%WEASEL_BUILD%-%GIT_HASH%-%BUILD_TIMESTAMP%-installer.exe
    name: ThuanTaigi

#deploy:
#  release: ThuanTaigi-Windows-v%WEASEL_VERSION%.%WEASEL_BUILD%-%GIT_HASH%-%BUILD_TIMESTAMP%
#  description: 'ThuanTaigi-Windows Release'
#  provider: GitHub
#  auth_token:
#    secure: QYElUlaZayQxjLn83N/BwkuePDbwhXf0cI6q0BqimbNQ+2DCU4WhDjyehZ6Jm1Dq
#  draft: true
#  prerelease: false
#  force_update: true

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
