environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CMAKE_GENERATOR: Visual Studio 15 2017
  PLATFORM_TOOLSET: v141_xp
  APPVEYOR_RDP_PASSWORD: Pass1234

init:
  - git --version
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master
    - kai_sanphin_mia

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

cache:
  - boost.cached -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage_x64 -> appveyor_build_boost.bat

install:
  - .\appveyor.install.bat

build_script:
  - if "%APPVEYOR_REPO_TAG%" == "false" set WEASEL_BUILD=%APPVEYOR_BUILD_NUMBER%
  - .\build.bat data hant installer

artifacts:
  - path: output\archives\ThuanTaigi-v$(WEASEL_VERSION).$(WEASEL_BUILD)-installer.exe
    name: ThuanTaigi

deploy:
  release: ThuanTaigi-v$(WEASEL_VERSION).$(WEASEL_BUILD)
  description: 'ThuanTaigi Release'
  provider: GitHub
  auth_token:
    secure: QYElUlaZayQxjLn83N/BwkuePDbwhXf0cI6q0BqimbNQ+2DCU4WhDjyehZ6Jm1Dq
  draft: true
  prerelease: false
  force_update: true
